// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('myApp', []);

app.controller('NameCaculatorController', function($scope) {
  var calculatNumericForString;
  $scope.name = '';
  $scope.totalValue = 0;
  $scope.displayNumeric = function() {
    var totalNameValue;
    totalNameValue = calculatNumericForString($scope.name);
    return $scope.totalValue = totalNameValue;
  };
  return calculatNumericForString = function(string) {
    var i, len, n, totalStringValue;
    totalStringValue = 0;
    for (i = 0, len = string.length; i < len; i++) {
      n = string[i];
      totalStringValue += n.charCodeAt();
    }
    return totalStringValue;
  };
});
