// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  angular.module('MsgApp', []).controller('MsgController', function($scope) {
    $scope.name = 'Luis';
    $scope.state = 'tux';
    $scope.sayMessage = function() {
      return 'Luis likes to eat healthy snacks at night';
    };
    return $scope.feedLuis = function() {
      return $scope.state = 'tux_dos';
    };
  });

}).call(this);
