// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  angular.module('DIApp', []).controller('DIController', function($scope, $filter) {
    $scope.name = 'Luis';
    return $scope.upper = function() {
      var upCase;
      upCase = $filter('uppercase');
      return $scope.name = upCase($scope.name);
    };
  });

}).call(this);
